In [1]:
import numpy as np
from sklearn import preprocessing

In [4]:
x = np.array([[1,-1,2],[2,0,0],[0,1,-1]],dtype=float)
x

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [6]:
x_scaled  = preprocessing.scale(x)

In [9]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [10]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [11]:
scaler = preprocessing.StandardScaler()

In [12]:
scaler.fit(x)

StandardScaler()

In [13]:
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [14]:
x_test = [[1,1,0]]

In [15]:
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])