In [1]:
import numpy as np

In [5]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]])

In [6]:
X.shape, Y.shape

((4, 2), (1, 4))

In [9]:
Y = Y.T

In [10]:
Y.shape

(4, 1)

In [12]:
def sig(z):
    return 1 / (1+ np.exp(-z))

## No hidden layeres

In [23]:
weights =2* np.random.random((2,1)) - 1
bias = 2*np.random.random(1)-1
weights,bias

(array([[0.3601241 ],
        [0.67360356]]),
 array([0.82276683]))

In [24]:
output0 = X

In [26]:
output = sig(np.dot(output0, weights)+bias)
output

array([[0.69482335],
       [0.81703251],
       [0.7654672 ],
       [0.86488783]])

## With hidden layers