In [2]:
import numpy as np

In [3]:
sample_array = np.array([1,2,3])

In [4]:
sample_array

array([1, 2, 3])

In [6]:
ones_float = np.ones(20)
ones_float

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [7]:
ones_int = np.ones(20, int)
ones_int

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
zeros = np.zeros((2,3))

In [12]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

* arange(start,stop,step): Returns evenly spaced values within a given interval

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10, 2)

array([3, 5, 7, 9])

In [15]:
random_array = np.random.randint(0, 20)

In [16]:
random_array

18

In [17]:
random_array = np.random.randint(0, 10, size =(3,5))

In [18]:
random_array

array([[3, 9, 6, 9, 9],
       [5, 6, 1, 2, 4],
       [0, 9, 0, 0, 9]])

In [19]:
random_array.size

15

In [20]:
random_array.shape

(3, 5)

In [22]:
random_3 = np.random.rand(5,3)
random_3

array([[0.77434304, 0.85938421, 0.43961291],
       [0.5327585 , 0.78100144, 0.17524043],
       [0.89380534, 0.40924817, 0.77352267],
       [0.96137822, 0.74360448, 0.0877006 ],
       [0.71586169, 0.20039758, 0.06494603]])