# Arithmetic 

In [1]:
import numpy as np

In [2]:
ones = np.ones(3)

In [3]:
a1 = np.array([2,3,4])

In [4]:
ones + a1

array([3., 4., 5.])

In [5]:
a1 - ones

array([1., 2., 3.])

In [6]:
a1 * ones

array([2., 3., 4.])

In [7]:
a1 / ones

array([2., 3., 4.])