In [1]:
import numpy as np

In [4]:
l = [1,2, 3]
np.array(l)

array([1, 2, 3])

In [7]:
l1 = [1,2,"3"]
np.array(l1)

array(['1', '2', '3'], dtype='<U11')

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
a = np.zeros(10)
a.dtype

dtype('float64')

In [11]:
a = np.zeros(10, int)

In [12]:
print(a.dtype)
a

int32


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
x = np.array([0,1,2,3])
x.shape

(4,)

## Numpy Operations

In [18]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a+2)
print(a+b)

[3 4 5]
[ 6  8 10]


In [19]:
x = np.array([1,2,3])
y = np.array([1,2])

In [20]:
x+y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [21]:
print(a*2)
print(a**2)
print(a**b)

[2 4 6]
[1 4 9]
[   1   64 2187]


In [22]:
a.mean()

2.0

In [23]:
a.sum()

6

In [24]:
np.array([5,1,2,1]).mean()

2.25

In [26]:
a = np.matrix('1,2,4; 3,4,5')
a.shape

(2, 3)

In [27]:
np.sum([[0,1],[0,5]], axis = 1)

array([1, 5])