In [2]:
import numpy as np

In [18]:
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [19]:
random_array_4

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [20]:
np.random.seed(seed=0)
random_5 = np.random.randint(10,size=(5,3))
random_5

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])