In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
              [4, 5, 6.3]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13,14,15],
             [16,17,18]]])

In [4]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [5]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.3]]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a2_reshape = a2.reshape(2,3,1)

In [11]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [100.8, 107.1, 113.4]]])

In [12]:
a2_reshape

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.3]]])

In [13]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.3]])

## Transpose

In [14]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.3]])

# Dot Product

In [15]:
np.random.seed(0)
mat1= np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size=(5,3))

In [16]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [17]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [18]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [20]:
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])