## Find unique elements in the array

In [2]:
import numpy as np

In [3]:
random_array = np.random.randint(20, size=(5,3))

In [4]:
np.unique(random_array)

array([ 0,  1,  2,  4,  5,  9, 10, 12, 13, 16])

# Viewing Arrays and matrices


In [5]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
              [4, 5, 6.3]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13,14,15],
             [16,17,18]]])

In [6]:
a1[0]

1

In [7]:
a2[0]

array([1., 2., 3.])

In [8]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
 a3[:2,:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [13]:
a2 = np.array([[1,2,3],
              [4, 5, 6.3]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13,14,15],
             [16,17,18]]])

In [15]:
a3 * a1

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

## Manipulating Arrays 2

In [17]:
massive_array = np.random.random(100000)
massive_array

array([0.9302537 , 0.85463177, 0.56895749, ..., 0.27614256, 0.99592085,
       0.31169347])

In [18]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

13.5 ms ± 2.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
58.3 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [19]:
np.max(massive_array)

0.9999998406973233

In [20]:
np.min(massive_array)

4.239322013765978e-06

In [21]:
np.std(massive_array)

0.28845288533751856

In [22]:
np.var(massive_array)

0.08320506705953963

### Reshape a2 to be compatible with a3